fix: es8316: add missing Mic devices
radxa-pkg/radxa-alsa-config pull request #7
Opened 2024-09-09 06:26 UTC by CodeChenL

* close https://github.com/radxa-pkg/radxa-alsa-config/issues/6

* This config come from https://github.com/alsa-project/alsa-ucm-conf/blob/9e245901aedee9efd5ede249dc8ba3efc747f7bf/ucm2/Rockchip/es8316/HiFi.conf#L29-L42

2024-09-09 06:28 UTC, CodeChenL commented
@RadxaYuntian request a review

2024-09-09 06:31 UTC, RadxaYuntian commented on src/alsa/ucm2/conf.d/rockchip-es8316/HiFi.conf
> +		cset "name='Differential Mux' lin1-rin1"
我们原理图用的应该是lin2-rin2。你有验证能否正常工作么？

2024-09-09 06:32 UTC, RadxaYuntian requested changes

2024-09-09 06:32 UTC, RadxaYuntian commented on src/alsa/ucm2/conf.d/rockchip-es8316/HiFi.conf
> +		CapturePriority 100
```suggestion
		CapturePriority 500
```
跟输出保持一致

2024-09-09 06:32 UTC, RadxaYuntian commented
另外也要测试其他的产品。我们大多数都有8316，可以在内核dts搜索对应compatible

2024-09-09 06:33 UTC, CodeChenL commented on src/alsa/ucm2/conf.d/rockchip-es8316/HiFi.conf
> +		cset "name='Differential Mux' lin1-rin1"
有验证正常，就是有点底噪，可能是办公室的，我换成lin2-rin2试试

2024-09-09 07:43 UTC, CodeChenL commented
已于rock4se bullseye和rock5b bookworm测试没问题，其他设备原理图也是lin2-rin2

2024-09-09 08:51 UTC, RadxaYuntian requested changes
squash

2024-09-10 02:11 UTC, RadxaYuntian approved these changes

2024-09-10 02:12 UTC, merged